---
- name: Ensure systemd unit file
  ansible.builtin.copy:
    src: tmp.mount
    dest: /etc/systemd/system/tmp.mount
    owner: root
    group: root
    mode: "06440"
  become: true
  become_user: root

- name: Enable and start the tmp.mount unit
  ansible.builtin.systemd:
    state: started
    enabled: true
    daemon_reload: true
    name: tmp.mount
  become: true
  become_user: root
